name: Build SpotBetter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot perl git wget unzip clang
          wget https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Download iOS SDK
        run: |
          wget -O iPhoneOS16.2.sdk.tar.xz https://github.com/xybp888/iOS-SDKs/releases/download/sdk/iPhoneOS16.2.sdk.tar.xz
          mkdir -p $HOME/theos/sdks
          tar -xJf iPhoneOS16.2.sdk.tar.xz -C $HOME/theos/sdks

      - name: Build
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean package

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotbetter-deb
          path: ./*.deb